mmsr_solar:
  outputs:
    dev:
      type: postgres
      host: 10.101.4.88
      user: juice
      password: "Baramulti1!"
      port: 5432
      dbname: MMSR
      schema: public  # Create models in public with dbt_ prefix
      threads: 1
      
  target: dev

