"""Metadata for dbt seeds used by Seed Manager. Delimiters match dbt_project.yml where set."""
from __future__ import annotations

SEEDS: dict[str, dict] = {
    "seed_site_config": {
        "display": "Site Config",
        "description": "Kapasitas, tarif, urutan site, tanggal mulai kalkulasi.",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["Site"],
        "column_hints": {},
    },
    "seed_meter_config_override": {
        "display": "Meter Config Override",
        "description": "Override atribut meter (voltage, type, polarity, phase swap).",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["Source", "esn_code"],
        "column_hints": {},
    },
    "seed_sensor_config_override": {
        "display": "Sensor Config Override",
        "description": "Override tipe sensor dan kapasitas.",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["Source", "device_id"],
        "column_hints": {},
    },
    "seed_site_merge": {
        "display": "Site Merge",
        "description": "Gabung plant_code FusionSolar ke logical site.",
        "ui_type": "form",
        "delimiter": ",",
        "required_columns": ["plant_code", "logical_plant_code"],
        "column_hints": {},
    },
    "seed_site_module_spec": {
        "display": "Site Module Spec",
        "description": "Spesifikasi modul per site dan periode.",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["site_id", "module_wp", "valid_from"],
        "column_hints": {},
    },
    "seed_issue_dates": {
        "display": "Issue Dates",
        "description": "Tanggal gangguan per site.",
        "ui_type": "form",
        "delimiter": ",",
        "required_columns": ["site_id", "issue_date"],
        "column_hints": {},
    },
    "seed_cleaning_log": {
        "display": "Cleaning Log",
        "description": "Log pembersihan panel.",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["asset_id", "cleaning_date"],
        "column_hints": {},
    },
    "seed_weekly_log": {
        "display": "Weekly Log",
        "description": "Log mingguan operasional.",
        "ui_type": "form",
        "delimiter": ",",
        "required_columns": ["log_date", "site_id"],
        "column_hints": {},
    },
    "seed_ghi_adjustment_daily": {
        "display": "GHI Adjustment Daily",
        "description": "Koreksi GHI harian.",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["site_name", "date_key", "ghi_adjusted_value"],
        "column_hints": {},
    },
    "seed_energy_adjustment_daily": {
        "display": "Energy Adjustment Daily",
        "description": "Koreksi energi harian.",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["site_name", "date_key", "energy_adjusted_value"],
        "column_hints": {},
    },
    "seed_poa_sensor_config": {
        "display": "POA Sensor Config",
        "description": "Sensor POA per orientasi.",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["site_id", "orient_code", "poa_sensor_id"],
        "column_hints": {},
    },
    "seed_sensor_site_mapping": {
        "display": "Sensor Site Mapping",
        "description": "Pemetaan sensor ke logical site.",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["device_id", "logical_site_id"],
        "column_hints": {},
    },
    "seed_meter_site_mapping": {
        "display": "Meter Site Mapping",
        "description": "Pemetaan meter ke logical site.",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["device_id", "logical_device_id"],
        "column_hints": {},
    },
    "seed_inverter_site_mapping": {
        "display": "Inverter Site Mapping",
        "description": "Pemetaan inverter ke logical device.",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["device_id", "logical_device_id"],
        "column_hints": {},
    },
    "seed_site_equipment_config": {
        "display": "Site Equipment Config",
        "description": "Model modul & inverter per site.",
        "ui_type": "form",
        "delimiter": ";",
        "required_columns": ["source", "site_id", "pv_module_model", "inverter_model"],
        "column_hints": {},
    },
    "seed_inverter_config": {
        "display": "Inverter Config",
        "description": "Master inverter per site.",
        "ui_type": "upload",
        "delimiter": ";",
        "required_columns": ["source", "site_id", "inverter_no", "inverter_id"],
        "column_hints": {},
    },
    "seed_inverter_string_layout": {
        "display": "Inverter String Layout",
        "description": "Layout string per MPPT.",
        "ui_type": "upload",
        "delimiter": ";",
        "required_columns": ["source", "site_id", "inverter_id", "mppt_no", "string_no"],
        "column_hints": {},
    },
    "seed_inverter_string_poa_mapping": {
        "display": "Inverter String POA Mapping",
        "description": "String ke sensor POA.",
        "ui_type": "upload",
        "delimiter": ";",
        "required_columns": ["source", "site_id", "inverter_id", "string_number", "poa_sensor_id"],
        "column_hints": {},
    },
    "seed_inverter_model_master": {
        "display": "Inverter Model Master",
        "description": "Spesifikasi teknis model inverter.",
        "ui_type": "upload",
        "delimiter": ";",
        "required_columns": ["manufacturer", "model"],
        "column_hints": {},
    },
    "seed_pv_module_model_master": {
        "display": "PV Module Model Master",
        "description": "Spesifikasi teknis modul PV.",
        "ui_type": "upload",
        "delimiter": ";",
        "required_columns": ["manufacturer", "model"],
        "column_hints": {},
    },
    "seed_daily_simulation_target": {
        "display": "Daily Simulation Target",
        "description": "Target simulasi harian (GHI, POA, energi, PR).",
        "ui_type": "upload",
        "delimiter": ";",
        "required_columns": ["Site_Name", "Site_Code", "Date"],
        "column_hints": {
            "_template": (
                "Header harus **persis** sama seed di repo. Contoh:\n"
                "`Site_Name;Site_Code;Week;Month;Date;GHI;POA;"
                "Energy Simulation (MW);Energy Target (MW);"
                "Daily PR POA Simulation;Daily PR POA Target;GHI vs POA;"
                "Daily PR GHI Simulation;Daily PR GHI Target`\n\n"
                "CSV boleh koma atau titik koma (auto-detect). "
                "Nama seperti `Energy Simulation(kWh/day)` **tidak** sama dengan `Energy Simulation (MW)`."
            ),
        },
    },
    "seed_yearly_simulation_target": {
        "display": "Yearly Simulation Target",
        "description": "Target energi tahunan.",
        "ui_type": "upload",
        "delimiter": ";",
        "required_columns": ["Site_Name", "Site_Code", "Year"],
        "column_hints": {},
    },
    "seed_daily_kpi_monthly": {
        "display": "Daily KPI Monthly",
        "description": "KPI energi bulanan.",
        "ui_type": "upload",
        "delimiter": ",",
        "required_columns": ["site_id", "Year", "Month"],
        "column_hints": {},
    },
    "seed_string_module_override": {
        "display": "String Module Override",
        "description": "Override Wp per string.",
        "ui_type": "upload",
        "delimiter": ";",
        "required_columns": ["site_id", "inverter_id", "mppt_no", "string_no"],
        "column_hints": {},
    },
    "seed_monthly_simulation_target": {
        "display": "Monthly Simulation Target (disabled di dbt)",
        "description": "Seed ini +enabled: false di dbt_project — hanya untuk referensi/edit file.",
        "ui_type": "upload",
        "delimiter": ",",
        "required_columns": ["Site_Name", "Site_Code", "Month"],
        "column_hints": {},
    },
    "seed_metric_mapper": {
        "display": "Metric Mapper",
        "description": "Pemetaan metric_id platform.",
        "ui_type": "readonly",
        "delimiter": ",",
        "required_columns": ["platform", "metric_id"],
        "column_hints": {},
    },
}

SEED_GROUPS: dict[str, list[str]] = {
    "Konfigurasi Site": [
        "seed_site_config",
        "seed_site_merge",
        "seed_site_equipment_config",
        "seed_site_module_spec",
    ],
    "Konfigurasi Inverter": [
        "seed_inverter_config",
        "seed_inverter_site_mapping",
        "seed_inverter_string_layout",
        "seed_inverter_string_poa_mapping",
        "seed_inverter_model_master",
        "seed_string_module_override",
    ],
    "Konfigurasi Meter": [
        "seed_meter_config_override",
        "seed_meter_site_mapping",
    ],
    "Konfigurasi Sensor": [
        "seed_sensor_config_override",
        "seed_sensor_site_mapping",
        "seed_poa_sensor_config",
    ],
    "Target & KPI": [
        "seed_daily_simulation_target",
        "seed_yearly_simulation_target",
        "seed_daily_kpi_monthly",
        "seed_monthly_simulation_target",
        "seed_pv_module_model_master",
    ],
    "Log Operasional": [
        "seed_issue_dates",
        "seed_cleaning_log",
        "seed_weekly_log",
        "seed_ghi_adjustment_daily",
        "seed_energy_adjustment_daily",
    ],
    "Referensi Sistem": [
        "seed_metric_mapper",
    ],
}
